---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-cd36007dd9f33cf34f7bcd8156183878
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/kjwierenga/gitops-config.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/kjwierenga/podinfo-deploy.git
